name: AuthLock
description: Bringing two factor authentication into Minecraft.
main: me.riley.authlock.bukkit.AuthLock
version: ${project.version}
commands:
  2fa:
    aliases: [twofactorauth,twofactorauthentication,twofa,tfa]